SELECT b.FIRST_DATE, a.DEAL, SUM(SUM) AS ARREARS, DAYS_PASSED
FROM PDCL AS a
         INNER JOIN
     (SELECT MIN(DATE) FIRST_DATE, DEAL, DATEDIFF(DAY, MIN(DATE), CURRENT_DATE) AS DAYS_PASSED
      FROM PDCL
      WHERE SUM > 0
      GROUP BY CUSTOMER, DEAL) AS b
     ON a.DEAL = b.DEAL
GROUP BY a.DEAL
HAVING ARREARS > 0
